"""
Report Generator - Multi-format output (Terminal, Markdown, JSON).

Generates formatted analysis reports using Rich for terminal display
and Jinja2 templates for file-based output.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

from src.models.analysis import RankedProject
from src.models.repository import Repository
from src.recommendation_templates import (
    TERMINAL_HEADER_TEMPLATE,
    TERMINAL_RANK_ROW_TEMPLATE,
    format_score_bar,
    format_tier_badge,
    truncate_text,
)
from src.utils.logger import get_logger

logger = get_logger(__name__)


class ReportGenerator:
    """Multi-format analysis report generator.

    Produces terminal-formatted and file-based reports from ranked
    project analysis results.
    """

    def __init__(self) -> None:
        pass

    def generate_terminal_report(
        self,
        query: str,
        ranked: List[RankedProject],
        duration_seconds: float = 0.0,
    ) -> str:
        """Generate a richly formatted terminal report."""
        lines: list[str] = []

        # Header / 头部
        lines.append(TERMINAL_HEADER_TEMPLATE.format(
            query=truncate_text(query, 42),
            count=len(ranked),
            top_pick=ranked[0].project.full_name if ranked else "None",
        ))
        lines.append("")

        # Ranking table / 排名表
        for rp in ranked[:15]:
            badge = format_tier_badge(rp.tier.value)
            bar = format_score_bar(rp.score.comprehensive)

            line = TERMINAL_RANK_ROW_TEMPLATE.format(
                rank=rp.rank,
                tier=f"[{badge}]",
                name=truncate_text(rp.project.full_name, 35),
                score=rp.score.comprehensive,
                stars=rp.project.stars,
            )
            lines.append(line)

        # Details for top 3 / 前3详情
        lines.append("\n--- Top Recommendations ---\n")
        for rp in ranked[:3]:
            highlights_str = "\n".join(f"  + {h}" for h in rp.highlights)
            concerns_str = "\n".join(f"  ! {c}" for c in rp.concerns) or "  None"

            detail = f"""  {rp.rank}. **{rp.project.full_name}** (Tier {rp.tier.value})
     | Score: {rp.score.comprehensive:.1f}/100  | Stars: {rp.project.stars:,}
     | {bar}
  |
  | Strengths:
{highlights_str}
  |
  | Concerns:
{concerns_str}
  |"""
            lines.append(detail)

        # Summary / 总结
        lines.append(f"\n{'=' * 60}\n")
        lines.append(f"Analysis completed in {duration_seconds:.1f} seconds.")
        lines.append(f"{len(ranked)} projects analyzed.\n")

        return "\n".join(lines)

    def generate_markdown_report(
        self,
        query: str,
        ranked: List[RankedProject],
        explanation: Optional[Dict[str, Any]] = None,
        timestamp: Optional[str] = None,
    ) -> str:
        """Generate a Markdown format report."""
        ts = timestamp or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        parts: list[str] = [
            "# Similar Project Rating Report\n",
            f"**Query:** {query}\n",
            f"**Generated:** {ts}\n",
            f"**Total Projects Analyzed:** {len(ranked)}\n",
        ]

        if explanation:
            parts.append("## Overview / 概览\n")
            parts.append(explanation.get("overview_en", "") + "\n")
            parts.append(explanation.get("overview_zh", "") + "\n")

        parts.append("\n## Ranked Results / 排名结果\n")
        parts.append("| # | Project | Score | Tier | Stars | Language |\n")
        parts.append("|---|---------|-------|------|-------|----------|\n")

        for rp in ranked[:20]:
            parts.append(
                f"| {rp.rank} | **{rp.project.full_name}** "
                f"| {rp.score.comprehensive:.1f} "
                f"| `{rp.tier.value}` "
                f"| {rp.project.stars:,} "
                f"| {rp.project.primary_language or '-'} |\n"
            )

        if explanation and explanation.get("conclusion_en"):
            parts.append(f"\n## Conclusion / 结论\n")
            parts.append(explanation["conclusion_en"] + "\n")
            if explanation.get("conclusion_zh"):
                parts.append(explanation["conclusion_zh"] + "\n")

        parts.append("\n---\n*Generated by Similar Project Rating System*\n")

        return "".join(parts)

    def generate_json_report(
        self,
        query: str,
        ranked: List[RankedProject],
        explanation: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Generate a structured JSON report."""
        return {
            "version": "1.0",
            "metadata": {
                "query": query,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "total_projects": len(ranked),
            },
            "ranking_summary": {
                "top_pick": ranked[0].project.full_name if ranked else "",
                "tier_distribution": self._count_tiers(ranked),
            },
            "projects": [
                {
                    "rank": rp.rank,
                    "full_name": rp.project.full_name,
                    "description": rp.project.description,
                    "stars": rp.project.stars,
                    "language": rp.project.primary_language,
                    "score": round(rp.score.comprehensive, 1),
                    "tier": rp.tier.value,
                    "highlights": rp.highlights,
                    "concerns": rp.concerns,
                    "url": rp.project.html_url or rp.project.url,
                }
                for rp in ranked
            ],
            "explanation": explanation or {},
        }

    @staticmethod
    def _count_tiers(ranked: List[RankedProject]) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        for rp in ranked:
            counts[rp.tier.value] = counts.get(rp.tier.value, 0) + 1
        return counts


__all__ = ["ReportGenerator"]
