"""
Recommendation Output Templates.

Provides template strings and formatting helpers for consistent
recommendation report generation across terminal, Markdown, and JSON outputs.

推荐输出模板。
为终端、Markdown和JSON输出的统一推荐报告生成提供
模板字符串和格式化辅助工具。
"""

from __future__ import annotations

from typing import Any, Dict, List


# ===========================================================================
# Terminal Report Templates / 终端报告模板
# ===========================================================================

TERMINAL_HEADER_TEMPLATE = """\
╔════════════════════════════════════════════════════╗
║   Similar Project Rating - Analysis Results       ║
║   相似项目评分系统 - 分析结果                       ║
╠════════════════════════════════════════════════════╣
║ Query: {query:<42} ║
║ Analyzed: {count:>3} projects | Top pick: {top_pick:<20}  ║
╚════════════════════════════════════════════════════╝
"""


TERMINAL_RANK_ROW_TEMPLATE = (
    "  {rank:>2}. [{tier}] {name:<35} Score:{score:>5.1f} Stars:{stars:>6,}"
)


TERMINAL_DETAIL_TEMPLATE = """\
  ┌─ {name} (Tier {tier}) ─────────────────────┐
  │ Score: {score:.1f}/100  |  Stars: {stars:,}  |  Lang: {lang}
  │
  │ Strengths:
  {highlights}
  │
  │ Concerns:
  {concerns}
  └──────────────────────────────────────────────┘
"""


# ===========================================================================
# Markdown Report Templates / Markdown报告模板
# ===========================================================================

MARKDOWN_REPORT_TEMPLATE = """\
# Similar Project Rating Report
# 相似项目评分报告

**Query:** {query}
**Generated:** {timestamp}
**Total Projects Analyzed:** {count}

## Overview / 概览

{overview}

## Detailed Results / 详细结果

{details}

## Conclusion / 结论

{conclusion}

---
*Report generated by Similar Project Rating System v{version}*
*由相似项目评分系统 v{version} 自动生成*
"""


MARKDOWN_PROJECT_SECTION_TEMPLATE = """\
### #{rank}. **{name}** `{tier}` — Score: **{score}/100**

| Metric | Value |
|--------|-------|
| Stars | {stars:,} |
| Language | {lang} |
| URL | [View on GitHub]({url}) |

**Strengths / 优势:**
{highlights_md}

**Concerns / 注意事项:**
{concerns_md}

**Recommended For / 推荐用途:**
{use_cases_md}

{verdict}
"""


# ===========================================================================
# JSON Report Structure Templates / JSON报告结构模板
# ===========================================================================

JSON_REPORT_STRUCTURE = {
    "version": "1.0",
    "metadata": {
        "query": "",
        "generated_at": "",
        "system_version": "",
        "total_projects": 0,
    },
    "ranking_summary": {
        "top_pick": "",
        "tier_distribution": {},
    },
    "projects": [],
    "comparison_table": {"headers": [], "rows": []},
    "explanation": {
        "overview_en": "",
        "overview_zh": "",
        "conclusion_en": "",
        "conclusion_zh": "",
    },
}


# ===========================================================================
# Formatting Helpers / 格式化辅助工具
# ===========================================================================

def format_score_bar(score: float, width: int = 20) -> str:
    """Create a visual ASCII bar representing a 0-100 score.

    创建表示0-100分数的可视化ASCII条形图。

    Args:
        score: Numeric score between 0 and 100.
               0到100之间的数值分数。
        width: Character width of the bar.
                 条形的字符宽度。

    Returns:
        String like '[████████░░░░░░░░] 50%'.
         类似'[████████░░░░░░░░] 50%'的字符串。
    """
    filled = int((score / 100.0) * width)
    empty = width - filled
    bar = "█" * filled + "░" * empty
    return f"[{bar}] {score:5.1f}"


def format_tier_badge(tier: str) -> str:
    """Format a tier label with color-like prefix for terminals.

    为终端格式化带颜色类前缀的等级标签。

    Args:
        tier: Single character tier ('S', 'A', 'B', 'C', 'D').
              单字符等级（'S'、'A'、'B'、'C'、'D'）。

    Returns:
        Formatted badge string like '[S]'.
         格式化的徽章字符串如'[S]'。
    """
    badges = {
        "S": "[S]",  # Would be colored green in real terminal / 在真实终端中会显示绿色
        "A": "[A]",
        "B": "[B]",
        "C": "[C]",
        "D": "[D]",
    }
    return badges.get(tier.upper(), "[?]")


def format_highlights_list(highlights: List[str], indent: int = 4) -> str:
    """Format highlight items into a bulleted list string.

    将高亮项格式化为项目符号列表字符串。

    Args:
        highlights: List of highlight strings.
                   高亮字符串列表。
        indent: Spaces of indentation per item.
                 每项缩进空格数。

    Returns:
        Multi-line bulleted string.
         多行项目符号字符串。
    }
    prefix = " " * indent
    if not highlights:
        return f"{prefix}- No notable strengths identified."
    return "\n".join(f"{prefix}- {h}" for h in highlights)


def format_concerns_list(concerns: List[str], indent: int = 4) -> str:
    """Format concern items into a bulleted list string.

    将关注项格式化为项目符号列表字符串。

    Args:
        concerns: List of concern strings.
                  关注字符串列表。
        indent: Spaces of indentation per item.
                 每项缩进空格数。

    Returns:
        Multi-line bulleted string.
         多行项目符号字符串。
    }
    prefix = " " * indent
    if not concerns:
        return f"{prefix}- No significant concerns."
    return "\n".join(f"{prefix}- {c}" for c in concerns)


def truncate_text(text: str, max_length: int = 80) -> str:
    """Truncate text with ellipsis if it exceeds maximum length.

    如果文本超过最大长度则截断并加省略号。

    Args:
        text: Input text string.
              输入文本字符串。
        max_length: Maximum allowed character count.
                   最大允许字符数。

    Returns:
        Truncated string or original if within limit.
             截断字符串或如未超限则返回原文。
    """
    if len(text) <= max_length:
        return text
    return text[: max_length - 3] + "..."


__all__ = [
    "TERMINAL_HEADER_TEMPLATE",
    "TERMINAL_RANK_ROW_TEMPLATE",
    "TERMINAL_DETAIL_TEMPLATE",
    "MARKDOWN_REPORT_TEMPLATE",
    "MARKDOWN_PROJECT_SECTION_TEMPLATE",
    "JSON_REPORT_STRUCTURE",
    "format_score_bar",
    "format_tier_badge",
    "format_highlights_list",
    "format_concerns_list",
    "truncate_text",
]
