"""
Search Domain Models.

Data classes representing search queries, keyword groups,
filter results, and other search-related entities.

搜索领域模型.
表示搜索查询,关键词组,过滤结果和其他搜索相关实体的dataclass.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from src.models.repository import Repository


@dataclass
class KeywordGroup:
    """A group of related keywords for GitHub search.

    Generated by AI from user's natural language query, each group targets
    a specific aspect (functionality, tech stack, use case, implementation).

    由AI从用户自然语言查询生成的每组关键词针对特定方面
    (功能,技术栈,用例,实现方式).

    Attributes:
        primary: Primary/main search keyword (required).
                 主搜索关键词(必需).
        extensions: Supplementary/related keywords to broaden or refine search.
                   补充/相关关键词,用于扩展或细化搜索.
        language: Optional programming language filter for results (e.g., 'Python').
                  结果的可选编程语言过滤器(例如'Python').
        category: Semantic classification of this keyword group ('functionality',
                  'tech_stack', 'use_case', 'implementation').
                  此关键词组的语义分类('functionality','tech_stack','use_case','implementation').
        rationale: AI-generated explanation of why these keywords are relevant.
                  AI生成的关于这些关键词相关性的解释.
    """
    primary: str = ""
    extensions: List[str] = field(default_factory=list)
    language: Optional[str] = None
    category: str = ""
    rationale: str = ""

    def build_search_query(self) -> str:
        """Build a GitHub search query string from this group.

        Combines primary keyword with extensions using OR logic,
        optionally adding language filter.

        从此组构建GitHub搜索查询字符串.
使用OR逻辑组合主关键词和扩展词,可选添加语言过滤器.

        Returns:
            Formatted GitHub search query string.
             格式化的GitHub搜索查询字符串.
        """
        parts = [self.primary]
        parts.extend(f"{ext}" for ext in self.extensions)
        query = " OR ".join(parts)
        if self.language:
            query += f" language:{self.language}"
        return query


@dataclass
class SearchQuery:
    """User's original search request and context.

    Wraps the user's natural language input with metadata about
    how it was processed and what options were selected.

    用户原始搜索请求和上下文.
包装用户自然语言输入,附带关于其如何处理
以及选择了哪些选项的元数据.

    Attributes:
        raw_query: Exact text entered by the user.
                  用户输入的确切文本.
        normalized: Cleaned/normalized version of the query.
                   清理/规范化后的查询版本.
        language_hint: Detected or user-specified preferred language.
                      检测到的或用户指定的首选语言.
        max_results: Maximum candidate results desired per keyword group.
                    每个关键词组期望的最大候选结果数.
        options: Additional search options provided.
                提供的其他搜索选项.
    """
    raw_query: str = ""
    normalized: str = ""
    language_hint: Optional[str] = None
    max_results: int = 50
    options: Dict[str, Any] = field(default_factory=dict)


@dataclass
class FilterResult:
    """Result of the relevance filtering process.

    Records which projects passed or failed relevance checking,
    including scores and reasons from the AI-based filter.

    相关性过滤过程的结果.
记录哪些项目通过了或未通过相关性检查,
包括来自AI过滤器的分数和原因.

    Attributes:
        input_count: Total candidates entering the filter.
                     进入过滤器的候选总数.
        kept: Projects that passed relevance threshold.
              通过相关性阈值的项目.
        removed: Projects that did not pass the threshold.
                未通过阈值的项目.
        removal_reasons: Map of project_full_name -> reason for removal.
                        project_full_name -> 移除原因的映射.
        relevance_scores: Map of project_full_name -> relevance score (0.0-1.0).
                         project_full_name -> 相关性分数(0.0-1.0)的映射.
        threshold: Minimum score required to pass filtering.
                  通过过滤所需的最低分数.
        applied_limit: Whether the max-projects cap was enforced (kept top-N by stars).
                      是否强制执行最大项目限制(按stars保留前N个).
        truncated_count: Number of additional relevant projects beyond the limit.
                       超出限制的额外相关项目数量.
    """
    input_count: int = 0
    kept: List[Repository] = field(default_factory=list)
    removed: List[Repository] = field(default_factory=list)
    removal_reasons: Dict[str, str] = field(default_factory=dict)
    relevance_scores: Dict[str, float] = field(default_factory=dict)
    threshold: float = 0.6
    applied_limit: bool = False
    truncated_count: int = 0

    @property
    def pass_rate(self) -> float:
        """Calculate the percentage of inputs that passed filtering.

        计算通过过滤输入的百分比.

        Returns:
            Pass rate as decimal (0.0 to 1.0), or 0 if no inputs.
            通过率的小数形式(0.0到1.0),如无输入则返回0.
        """
        if self.input_count == 0:
            return 0.0
        return len(self.kept) / self.input_count
